package discuswk2;
/* Travis VanArsdale
 *  8/29/2021
 *  This program will calculate interest generated, given both a starting amount and a return rate.
 */ 
import java.util.Scanner;

public class VanTravisDiscusswk2 {
	public static void main(String[] args) {
	Scanner inputs = new Scanner(System.in); 
	// Declaring variables
		double amount;
		double rate;
		double interest;
		
		System.out.println(" This program will calculate intrest generated in one year.");
		
		System.out.println("Please enter the initial amount in the account.");
		 amount = inputs.nextDouble(); // setting initial amount
		
		System.out.println("Please enter the anual interest rate as a percentage.");
		rate = inputs.nextDouble();  // setting interest rate
		
		interest = amount * (rate / 100); // calculating intrest earned
		
		System.out.println("The annual intrest generated by this account is " + interest + ".");
		inputs.close();
	}

}
